const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'
const SET_POINTS = 'SET_POINTS'
const GET_PLAYER = 'GET_PLAYER'
const SET_SELECTED_POINTS_VALUE = 'SET_SELECTED_POINTS_VALUE'
const SET_SELECTED_CELL = 'SET_SELECTED_CELL'
const GET_RESULTS = 'GET_RESULTS'
const ADD_PLAYER = 'ADD_PLAYER'

export {
  OPEN_MODAL,
  CLOSE_MODAL,
  SET_POINTS,
  GET_PLAYER,
  SET_SELECTED_POINTS_VALUE,
  SET_SELECTED_CELL,
  GET_RESULTS,
  ADD_PLAYER,
}
