const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'
const CLOSE_MODALS = 'CLOSE_MODALS'
const SET_POINTS = 'SET_POINTS'
const GET_PLAYER = 'GET_PLAYER'
const SET_SELECTED_POINTS_VALUE = 'SET_SELECTED_POINTS_VALUE'
const SET_SELECTED_CELL = 'SET_SELECTED_CELL'
const GET_RESULTS = 'GET_RESULTS'
const ADD_PLAYER = 'ADD_PLAYER'
const OPEN_NEGATIVE_NUMBERS_MODAL = 'OPEN_NEGATIVE_NUMBERS_MODAL'
const CLOSE_NEGATIVE_NUMBERS_MODAL = 'CLOSE_NEGATIVE_NUMBERS_MODAL'
const OPEN_BIG_NUMBERS_MODAL = 'OPEN_BIG_NUMBERS_MODAL'
const CLOSE_BIG_NUMBERS_MODAL = 'CLOSE_BIG_NUMBERS_MODAL'

export {
  OPEN_MODAL,
  CLOSE_MODAL,
  CLOSE_MODALS,
  SET_POINTS,
  GET_PLAYER,
  SET_SELECTED_POINTS_VALUE,
  SET_SELECTED_CELL,
  GET_RESULTS,
  ADD_PLAYER,
  OPEN_NEGATIVE_NUMBERS_MODAL,
  CLOSE_NEGATIVE_NUMBERS_MODAL,
  OPEN_BIG_NUMBERS_MODAL,
  CLOSE_BIG_NUMBERS_MODAL,
}
